name: Augment the SBOM
description: Augments the SBOM for the project
inputs:
  # no longer used
  silk_asset_group:
    description: The Silk Asset Group for the Project
    required: false
  sbom_in_path:
    description: The path of the input sbom file.
    default: sbom.json
  sbom_file_name:
    description: The name of the augmented sbom file.
    default: cyclonedx.sbom.json
  kondukto_sub_project:
    description: The Kondukto sub-project name (appended to the branch name)
    required: false
  artifactory_image:
    description: Image to use for artifactory
    default: artifactory.corp.mongodb.com/release-tools-container-registry-public-local/silkbomb:2.0

runs:
  using: composite
  steps:
    - name: Augments the SBOM file and writes it to the release assets and s3 assets folders
      shell: bash
      run: |
        set -eux
        if [ -n "${{ inputs.kondukto_sub_project }}" ]; then
          KONDUKTO_BRANCH="${GITHUB_REF_NAME}_${{ inputs.kondukto_sub_project }}"
        else
          KONDUKTO_BRANCH="${GITHUB_REF_NAME}"
        fi
        podman run --platform="linux/amd64" -it --rm -v ${RELEASE_ASSETS}:/pwd \
          --env-file=${SILKBOMB_ENVFILE} \
          ${{ inputs.artifactory_image }} \
          augment --sbom-in /pwd/${{ inputs.sbom_in_path }} --repo ${GITHUB_REPOSITORY} --branch ${KONDUKTO_BRANCH} --sbom-out /pwd/cyclonedx.sbom.json
        cp ${RELEASE_ASSETS}/cyclonedx.sbom.json ${S3_ASSETS}/${{ inputs.sbom_file_name }}